export function getCurrencySettings() {
  const currencySetting = localStorage.getItem('finai_currency_display') || 'USD ($)';
  if (currencySetting.includes('IDR') || currencySetting.includes('Rp')) {
    return { symbol: 'Rp', code: 'IDR', rate: 15000, locale: 'id-ID' };
  }
  if (currencySetting.includes('EUR') || currencySetting.includes('€')) {
    return { symbol: '€', code: 'EUR', rate: 0.92, locale: 'de-DE' };
  }
  if (currencySetting.includes('GBP') || currencySetting.includes('£')) {
    return { symbol: '£', code: 'GBP', rate: 0.78, locale: 'en-GB' };
  }
  // Default to USD
  return { symbol: '$', code: 'USD', rate: 1, locale: 'en-US' };
}

export function formatCurrency(amount: number, options?: { showSign?: boolean; decimals?: number }) {
  const { code, rate, locale } = getCurrencySettings();
  const converted = amount * rate;
  const isPositive = amount >= 0;
  
  const formatted = new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: code,
    minimumFractionDigits: options?.decimals !== undefined ? options.decimals : 2,
    maximumFractionDigits: options?.decimals !== undefined ? options.decimals : 2,
  }).format(Math.abs(converted));

  if (options?.showSign) {
    return `${isPositive ? '+' : '-'}${formatted}`;
  }
  return isPositive ? formatted : `-${formatted}`;
}

export function formatSimpleCurrency(amount: number) {
  return formatCurrency(amount, { decimals: 0 });
}

export function isZenModeEnabled() {
  return localStorage.getItem('finai_zen_mode') === 'true';
}

const translations: Record<string, Record<string, string>> = {
  'Bahasa Indonesia': {
    'Dashboard': 'Dasbor',
    'Welcome back': 'Selamat datang kembali',
    'Your financial overview is looking healthy today.': 'Gambaran keuangan Anda terlihat sehat hari ini.',
    'Transactions': 'Transaksi',
    'Savings Goals': 'Target Tabungan',
    'Reports': 'Laporan',
    'Profile': 'Profil',
    'Settings': 'Pengaturan',
    'Subscription': 'Langganan',
    'Support': 'Bantuan',
    'Add Transaction': 'Tambah Transaksi',
    'Total Combined Balance': 'Total Saldo Gabungan',
    'Checking': 'Rekening Giro',
    'Savings': 'Tabungan',
    'Investments': 'Investasi',
    '+2.4% from last month': '+2,4% dari bulan lalu',
    'Monthly Inflow': 'Pemasukan Bulanan',
    'Monthly Spending': 'Pengeluaran Bulanan',
    'Monthly Net Savings': 'Tabungan Bersih Bulanan',
    'Remaining of budget': 'Sisa anggaran',
    'Inflow': 'Pemasukan',
    'Outflow': 'Pengeluaran',
    'Savings Rate': 'Rasio Tabungan',
    'Target': 'Target',
    'Active Goals': 'Target Aktif',
    'Add Goal': 'Tambah Target',
    'Fund Goal': 'Isi Tabungan',
    'Recent Activity': 'Aktivitas Terbaru',
    'View All': 'Lihat Semua',
    'Income': 'Pendapatan',
    'Expense': 'Pengeluaran',
    'No transactions found': 'Transaksi tidak ditemukan',
    'Cash Flow Analytics': 'Analisis Aliran Kas',
    'Total Spending': 'Total Pengeluaran',
    'Net Savings': 'Tabungan Bersih',
    'Category Breakdown': 'Rincian Kategori',
    'Recent Reports': 'Laporan Terbaru',
    'Export Report': 'Ekspor Laporan',
    'Profile Settings': 'Pengaturan Profil',
    'General Preferences': 'Preferensi Umum',
    'Display Language': 'Bahasa Tampilan',
    'Currency Display': 'Tampilan Mata Uang',
    'Zen Mode': 'Mode Zen',
    'Security': 'Keamanan',
    'Save Changes': 'Simpan Perubahan',
    'Cancel': 'Batal',
    'Manage your basic account configurations and appearance.': 'Kelola konfigurasi dasar akun dan tampilan Anda.',
    'Select your preferred interface language.': 'Pilih bahasa tampilan antarmuka yang Anda inginkan.',
    'Set the primary currency for your financial reports.': 'Atur mata uang utama untuk laporan keuangan Anda.',
    'Search settings...': 'Cari pengaturan...',
    'Settings Saved Successfully': 'Pengaturan Berhasil Disimpan',
    'Help & Support Center': 'Pusat Bantuan & Dukungan',
    'Contact Support Desk': 'Hubungi Meja Dukungan',
    'Inquiry Message': 'Pesan Pertanyaan',
    'Submit Inquiry': 'Kirim Pertanyaan',
    'Frequently Asked Questions': 'Pertanyaan yang Sering Diajukan',
    'Search transactions...': 'Cari transaksi...',
    'Merchant Name': 'Nama Merchant',
    'Amount': 'Jumlah',
    'Category': 'Kategori',
    'Date': 'Tanggal',
    'Action': 'Tindakan',
    'Add New Transaction': 'Tambah Transaksi Baru',
    'Edit Transaction': 'Ubah Transaksi',
    'All Categories': 'Semua Kategori',
    'Weekly Avg': 'Rata-rata Mingguan',
    'No transaction logs found': 'Catatan transaksi tidak ditemukan',
    'Savings Goals Tracker': 'Pelacak Target Tabungan',
    'Create New Goal': 'Buat Target Baru',
    'Manage Goal Categories': 'Kelola Kategori Target',
    'Remaining': 'Sisa',
    'Fund': 'Isi',
    'Withdraw': 'Tarik',
    'Edit': 'Ubah',
    'Delete': 'Hapus',
    'Completed': 'Selesai',
    'Add Savings Goal': 'Tambah Target Tabungan',
    'Goal Title': 'Judul Target',
    'Target Amount': 'Jumlah Target',
    'Current Savings': 'Tabungan Saat Ini',
    'Create Goal': 'Buat Target',
    'Dukung Developer': 'Dukung Developer',
    'Dukung Pengembangan FINAI': 'Dukung Pengembangan FINAI',
    'Kontribusi Anda sangat berarti untuk membantu kami menjaga kualitas layanan, mengembangkan fitur baru, dan menjaga aplikasi ini tetap bebas dari iklan.': 'Kontribusi Anda sangat berarti untuk membantu kami menjaga kualitas layanan, mengembangkan fitur baru, dan menjaga aplikasi ini tetap bebas dari iklan.',
    'Pindai QR Code': 'Pindai QR Code',
    'Pindai menggunakan aplikasi dompet digital atau mobile banking Anda': 'Pindai menggunakan aplikasi dompet digital atau mobile banking Anda',
    'Scan via QRIS / Bank Transfer': 'Scan via QRIS / Bank Transfer',
    'Terima kasih atas segala bentuk kebaikan dan apresiasi Anda!': 'Terima kasih atas segala bentuk kebaikan dan apresiasi Anda!',
    'Financial freedom is available to those who learn about it and work for it.': 'Kebebasan finansial tersedia bagi mereka yang mempelajarinya dan mengusahakannya.',
    'Privacy Policy': 'Kebijakan Privasi',
    'Terms of Service': 'Ketentuan Layanan',
    'Spending Overview': 'Ikhtisar Pengeluaran',
    'A minimalist breakdown of your financial flows. Your spending': 'Analisis minimalis dari arus keuangan Anda. Pengeluaran Anda',
    'decreased': 'menurun',
    'increased': 'meningkat',
    'by': 'sebesar',
    'compared to the previous period.': 'dibandingkan periode sebelumnya.',
    'vs. prev. period': 'vs. periode sebelumnya',
    'No previous data to compare': 'Tidak ada data sebelumnya untuk dibandingkan',
    'Zen Mode is Active': 'Mode Zen Aktif',
    'Aggressive charts and complex visualization models have been suspended for a cleaner view.': 'Bagan agresif dan model visualisasi kompleks telah ditangguhkan untuk tampilan yang lebih bersih.',
    'Income vs. Expenses across the current semester': 'Pendapatan vs. Pengeluaran sepanjang semester berjalan',
    'Expenses': 'Pengeluaran',
    'No cash flow analytics data available': 'Tidak ada data analisis aliran kas yang tersedia',
    'Your income vs. expenses chart will be displayed here once you start adding transactions.': 'Bagan pendapatan vs. pengeluaran Anda akan ditampilkan di sini setelah Anda mulai menambahkan transaksi.',
    'Spending by Category': 'Pengeluaran berdasarkan Kategori',
    'No spending data available': 'Data pengeluaran tidak tersedia',
    'Your category spending breakdown will appear here once you record expenses.': 'Rincian pengeluaran kategori Anda akan muncul di sini setelah Anda mencatat pengeluaran.',
    'Historical Mutations': 'Mutasi Historis',
    'Select Billing Month': 'Pilih Bulan Penagihan',
    'No history available': 'Tidak ada riwayat tersedia',
    'Total Transactions:': 'Total Transaksi:',
    'items': 'item',
    'Net Cashflow:': 'Aliran Kas Bersih:',
    'View PDF': 'Lihat PDF',
    'Historical Transaction Statement': 'Laporan Transaksi Historis',
    'Financial Statement Report': 'Laporan Keuangan',
    'STATEMENT OF ACCOUNT': 'LAPORAN REKENING',
    'Period': 'Periode',
    'Generated': 'Dibuat',
    'at': 'pada',
    'Prepared For': 'Disiapkan Untuk',
    'Account Tier': 'Tingkat Akun',
    'Financial Metrics Summary': 'Ringkasan Metrik Keuangan',
    'Total Cash Inflow': 'Total Aliran Kas Masuk',
    'Total Cash Outflow': 'Total Aliran Kas Keluar',
    'Spending by Category Breakdown': 'Rincian Pengeluaran berdasarkan Kategori',
    'Proportion': 'Proporsi',
    'Transaction Details (Account Activity)': 'Detail Transaksi (Aktivitas Akun)',
    'This document is a certified summary of personal financial statements processed by FINAI. Information is prepared for reference purposes and is not formal legal tax auditing advice.': 'Dokumen ini adalah ringkasan tersertifikasi dari laporan keuangan pribadi yang diproses oleh FINAI. Informasi disiapkan untuk tujuan referensi dan bukan saran audit pajak hukum formal.',
    'Close': 'Tutup',
    'Download PDF': 'Unduh PDF',
  },
  'Español': {
    'Dashboard': 'Tablero',
    'Welcome back': 'Bienvenido de nuevo',
    'Your financial overview is looking healthy today.': 'Su resumen financiero se ve saludable hoy.',
    'Transactions': 'Transacciones',
    'Savings Goals': 'Objetivos de Ahorro',
    'Reports': 'Informes',
    'Profile': 'Perfil',
    'Settings': 'Ajustes',
    'Subscription': 'Suscripción',
    'Support': 'Soporte',
    'Add Transaction': 'Agregar Transacción',
    'Total Combined Balance': 'Saldo Total Combinado',
    'Checking': 'Corriente',
    'Savings': 'Ahorros',
    'Investments': 'Inversiones',
    '+2.4% from last month': '+2.4% desde el mes pasado',
    'Monthly Inflow': 'Entrada Mensual',
    'Monthly Spending': 'Gasto Mensual',
    'Monthly Net Savings': 'Ahorro Neto Mensual',
    'Remaining of budget': 'Restante del presupuesto',
    'Inflow': 'Entrada',
    'Outflow': 'Salida',
    'Savings Rate': 'Tasa de Ahorro',
    'Target': 'Objetivo',
    'Active Goals': 'Objetivos Activos',
    'Add Goal': 'Agregar Objetivo',
    'Fund Goal': 'Fondear Objetivo',
    'Recent Activity': 'Actividad Reciente',
    'View All': 'Ver Todo',
    'Income': 'Ingresos',
    'Expense': 'Gastos',
    'No transactions found': 'No se encontraron transacciones',
    'Cash Flow Analytics': 'Análisis de Flujo de Caja',
    'Total Spending': 'Gasto Total',
    'Net Savings': 'Ahorro Neto',
    'Category Breakdown': 'Desglose por Categoría',
    'Recent Reports': 'Informes Recientes',
    'Export Report': 'Exportar Informe',
    'Profile Settings': 'Ajustes de Perfil',
    'General Preferences': 'Preferencias Generales',
    'Display Language': 'Idioma de Pantalla',
    'Currency Display': 'Pantalla de Moneda',
    'Zen Mode': 'Modo Zen',
    'Security': 'Seguridad',
    'Save Changes': 'Guardar Cambios',
    'Cancel': 'Cancelar',
    'Manage your basic account configurations and appearance.': 'Administre sus configuraciones básicas de cuenta y apariencia.',
    'Select your preferred interface language.': 'Seleccione su idioma de interfaz preferido.',
    'Set the primary currency for your financial reports.': 'Establezca la moneda principal para sus informes financieros.',
    'Search settings...': 'Buscar ajustes...',
    'Settings Saved Successfully': 'Ajustes Guardados Exitosamente',
    'Help & Support Center': 'Centro de Ayuda y Soporte',
    'Contact Support Desk': 'Contactar Soporte',
    'Inquiry Message': 'Mensaje de Consulta',
    'Submit Inquiry': 'Enviar Consulta',
    'Frequently Asked Questions': 'Preguntas Frecuentes',
    'Search transactions...': 'Buscar transacciones...',
    'Merchant Name': 'Nombre del Comerciante',
    'Amount': 'Cantidad',
    'Category': 'Categoría',
    'Date': 'Fecha',
    'Action': 'Acción',
    'Add New Transaction': 'Agregar Nueva Transacción',
    'Edit Transaction': 'Editar Transacción',
    'All Categories': 'Todas las Categorías',
    'Weekly Avg': 'Promedio Semanal',
    'No transaction logs found': 'No se encontraron registros de transacciones',
    'Savings Goals Tracker': 'Seguimiento de Objetivos de Ahorro',
    'Create New Goal': 'Crear Nuevo Objetivo',
    'Manage Goal Categories': 'Administrar Categorías de Objetivo',
    'Remaining': 'Restante',
    'Fund': 'Fondear',
    'Withdraw': 'Retirar',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Completed': 'Completado',
    'Add Savings Goal': 'Agregar Objetivo de Ahorro',
    'Goal Title': 'Título del Objetivo',
    'Target Amount': 'Cantidad Objetivo',
    'Current Savings': 'Ahorro Actual',
    'Create Goal': 'Crear Objetivo',
    'Dukung Developer': 'Apoyar al Desarrollador',
    'Dukung Pengembangan FINAI': 'Apoyar el Desarrollo de FINAI',
    'Kontribusi Anda sangat berarti untuk membantu kami menjaga kualitas layanan, mengembangkan fitur baru, dan menjaga aplikasi ini tetap bebas dari iklan.': 'Su contribución es muy significativa para ayudarnos a mantener la calidad del servicio, desarrollar nuevas funciones y mantener esta aplicación libre de anuncios.',
    'Pindai QR Code': 'Escanear Código QR',
    'Pindai menggunakan aplikasi dompet digital atau mobile banking Anda': 'Escanee usando su billetera digital o aplicación de banca móvil',
    'Scan via QRIS / Bank Transfer': 'Escanear vía QRIS / Transferencia Bancaria',
    'Terima kasih atas segala bentuk kebaikan dan apresiasi Anda!': '¡Gracias por toda forma de amabilidad y aprecio!',
    'Financial freedom is available to those who learn about it and work for it.': 'La libertad financiera está disponible para aquellos que aprenden sobre ella y trabajan para conseguirla.',
    'Privacy Policy': 'Política de Privacidad',
    'Terms of Service': 'Términos de Servicio',
    'Spending Overview': 'Resumen de Gastos',
    'A minimalist breakdown of your financial flows. Your spending': 'Un desglose minimalista de sus flujos financieros. Su gasto',
    'decreased': 'disminuyó',
    'increased': 'aumentó',
    'by': 'en un',
    'compared to the previous period.': 'en comparación con el período anterior.',
    'vs. prev. period': 'vs. período anterior',
    'No previous data to compare': 'Sin datos anteriores para comparar',
    'Zen Mode is Active': 'El Modo Zen está Activo',
    'Aggressive charts and complex visualization models have been suspended for a cleaner view.': 'Los gráficos agresivos y los modelos complejos de visualización han sido suspendidos para una vista más limpia.',
    'Income vs. Expenses across the current semester': 'Ingresos vs. Gastos durante el semestre actual',
    'Expenses': 'Gastos',
    'No cash flow analytics data available': 'No hay datos de análisis de flujo de caja disponibles',
    'Your income vs. expenses chart will be displayed here once you start adding transactions.': 'Su gráfico de ingresos vs. gastos se mostrará aquí una vez que comience a agregar transacciones.',
    'Spending by Category': 'Gastos por Categoría',
    'No spending data available': 'No hay datos de gastos disponibles',
    'Your category spending breakdown will appear here once you record expenses.': 'Su desglose de gastos por categoría aparecerá aquí una vez que registre los gastos.',
    'Historical Mutations': 'Mutaciones Históricas',
    'Select Billing Month': 'Seleccionar Mes de Facturación',
    'No history available': 'Sin historial disponible',
    'Total Transactions:': 'Transacciones Totales:',
    'items': 'artículos',
    'Net Cashflow:': 'Flujo de Caja Neto:',
    'View PDF': 'Ver PDF',
    'Historical Transaction Statement': 'Estado de Transacciones Histórico',
    'Financial Statement Report': 'Informe de Estado Financiero',
    'STATEMENT OF ACCOUNT': 'ESTADO DE CUENTA',
    'Period': 'Período',
    'Generated': 'Generado',
    'at': 'a las',
    'Prepared For': 'Preparado Para',
    'Account Tier': 'Nivel de Cuenta',
    'Financial Metrics Summary': 'Resumen de Métricas Financieras',
    'Total Cash Inflow': 'Entrada de Efectivo Total',
    'Total Cash Outflow': 'Salida de Efectivo Total',
    'Spending by Category Breakdown': 'Desglose de Gastos por Categoría',
    'Proportion': 'Proporción',
    'Transaction Details (Account Activity)': 'Detalles de la Transacción (Actividad de la Cuenta)',
    'This document is a certified summary of personal financial statements processed by FINAI. Information is prepared for reference purposes and is not formal legal tax auditing advice.': 'Este documento es un resumen certificado de los estados financieros personales procesados por FINAI. La información se prepara para fines de referencia y no constituye un asesoramiento formal de auditoría fiscal legal.',
    'Close': 'Cerrar',
    'Download PDF': 'Descargar PDF',
  },
  'Français': {
    'Dashboard': 'Tableau de bord',
    'Welcome back': 'Bon retour',
    'Your financial overview is looking healthy today.': 'Votre aperçu financier semble sain aujourd\'hui.',
    'Transactions': 'Transactions',
    'Savings Goals': 'Objectifs d\'Épargne',
    'Reports': 'Rapports',
    'Profile': 'Profil',
    'Settings': 'Paramètres',
    'Subscription': 'Abonnement',
    'Support': 'Support',
    'Add Transaction': 'Ajouter une Transaction',
    'Total Combined Balance': 'Solde Total Combiné',
    'Checking': 'Chèque',
    'Savings': 'Épargne',
    'Investments': 'Investissements',
    '+2.4% from last month': '+2.4% par rapport au mois dernier',
    'Monthly Inflow': 'Entrée Mensuelle',
    'Monthly Spending': 'Dépenses Mensuelles',
    'Monthly Net Savings': 'Épargne Nette Mensuelle',
    'Remaining of budget': 'Reste du budget',
    'Inflow': 'Entrée',
    'Outflow': 'Sortie',
    'Savings Rate': 'Taux d\'Épargne',
    'Target': 'Cible',
    'Active Goals': 'Objectifs Actifs',
    'Add Goal': 'Ajouter un Objectif',
    'Fund Goal': 'Alimenter l\'Objectif',
    'Recent Activity': 'Activité Récente',
    'View All': 'Voir Tout',
    'Income': 'Revenus',
    'Expense': 'Dépenses',
    'No transactions found': 'Aucune transaction trouvée',
    'Cash Flow Analytics': 'Analyse des Flux de Trésorerie',
    'Total Spending': 'Dépenses Totales',
    'Net Savings': 'Épargne Nette',
    'Category Breakdown': 'Répartition par Catégorie',
    'Recent Reports': 'Rapports Récents',
    'Export Report': 'Exporter le Rapport',
    'Profile Settings': 'Paramètres du Profil',
    'General Preferences': 'Préférences Générales',
    'Display Language': 'Langue d\'Affichage',
    'Currency Display': 'Affichage de la Devise',
    'Zen Mode': 'Mode Zen',
    'Security': 'Sécurité',
    'Save Changes': 'Enregistrer les modifications',
    'Cancel': 'Annuler',
    'Manage your basic account configurations and appearance.': 'Gérez vos configurations de base de compte et l\'apparence.',
    'Select your preferred interface language.': 'Sélectionnez votre langue d\'interface préférée.',
    'Set the primary currency for your financial reports.': 'Définissez la devise principale pour vos rapports financiers.',
    'Search settings...': 'Rechercher des paramètres...',
    'Settings Saved Successfully': 'Paramètres enregistrés avec succès',
    'Help & Support Center': 'Centre d\'Aide & Support',
    'Contact Support Desk': 'Contacter le Support',
    'Inquiry Message': 'Message de demande',
    'Submit Inquiry': 'Soumettre la demande',
    'Frequently Asked Questions': 'Questions Fréquemment Posées',
    'Search transactions...': 'Rechercher des transactions...',
    'Merchant Name': 'Nom du Marchand',
    'Amount': 'Montant',
    'Category': 'Catégorie',
    'Date': 'Date',
    'Action': 'Action',
    'Add New Transaction': 'Ajouter une Nouvelle Transaction',
    'Edit Transaction': 'Modifier la Transaction',
    'All Categories': 'Toutes les Catégories',
    'Weekly Avg': 'Moyenne Hebdomadaire',
    'No transaction logs found': 'Aucun journal de transaction trouvé',
    'Savings Goals Tracker': 'Suivi des Objectifs d\'Épargne',
    'Create New Goal': 'Créer un Nouvel Objectif',
    'Manage Goal Categories': 'Gérer les Catégories d\'Objectifs',
    'Remaining': 'Restant',
    'Fund': 'Alimenter',
    'Withdraw': 'Retirer',
    'Edit': 'Modifier',
    'Delete': 'Supprimer',
    'Completed': 'Terminé',
    'Add Savings Goal': 'Ajouter un Objectif d\'Épargne',
    'Goal Title': 'Titre de l\'Objectif',
    'Target Amount': 'Montant Cible',
    'Current Savings': 'Épargne Actuelle',
    'Create Goal': 'Créer un Objectif',
    'Dukung Developer': 'Soutenir le Développeur',
    'Dukung Pengembangan FINAI': 'Soutenir le Développement de FINAI',
    'Kontribusi Anda sangat berarti untuk membantu kami menjaga kualitas layanan, mengembangkan fitur baru, dan menjaga aplikasi ini tetap bebas dari iklan.': 'Votre contribution est très précieuse pour nous aider à maintenir la qualité du service, développer de nouvelles fonctionnalités et garder cette application sans publicité.',
    'Pindai QR Code': 'Scanner le Code QR',
    'Pindai menggunakan aplikasi dompet digital atau mobile banking Anda': 'Scannez à l\'aide de votre portefeuille numérique ou de votre application de banque mobile',
    'Scan via QRIS / Bank Transfer': 'Scanner via QRIS / Transfert Bancaire',
    'Terima kasih atas segala bentuk kebaikan dan apresiasi Anda!': 'Merci pour toutes les formes de gentillesse et d\'appréciation !',
    'Financial freedom is available to those who learn about it and work for it.': 'La liberté financière est accessible à ceux qui s\'y informent et y travaillent.',
    'Privacy Policy': 'Politique de Confidentialité',
    'Terms of Service': 'Conditions d\'Utilisation',
    'Spending Overview': 'Aperçu des Dépenses',
    'A minimalist breakdown of your financial flows. Your spending': 'Une répartition minimaliste de vos flux financiers. Vos dépenses ont',
    'decreased': 'diminué',
    'increased': 'augmenté',
    'by': 'de',
    'compared to the previous period.': 'par rapport à la période précédente.',
    'vs. prev. period': 'vs. période précédente',
    'No previous data to compare': 'Aucune donnée précédente à comparer',
    'Zen Mode is Active': 'Le Mode Zen est Actif',
    'Aggressive charts and complex visualization models have been suspended for a cleaner view.': 'Les graphiques agressifs et les modèles de visualisation complexes ont été suspendus pour une vue plus propre.',
    'Income vs. Expenses across the current semester': 'Revenus vs. Dépenses sur le semestre en cours',
    'Expenses': 'Dépenses',
    'No cash flow analytics data available': 'Aucune donnée d\'analyse de flux de trésorerie disponible',
    'Your income vs. expenses chart will be displayed here once you start adding transactions.': 'Votre graphique revenus vs. dépenses s\'affichera ici une fois que vous aurez commencé à ajouter des transactions.',
    'Spending by Category': 'Dépenses par Catégorie',
    'No spending data available': 'Aucune donnée de dépenses disponible',
    'Your category spending breakdown will appear here once you record expenses.': 'La répartition de vos dépenses par catégorie apparaîtra ici une fois que vous aurez enregistré des dépenses.',
    'Historical Mutations': 'Mutations Historiques',
    'Select Billing Month': 'Sélectionner le Mois de Facturation',
    'No history available': 'Aucun historique disponible',
    'Total Transactions:': 'Transactions Totales:',
    'items': 'éléments',
    'Net Cashflow:': 'Flux de Trésorerie Net:',
    'View PDF': 'Voir le PDF',
    'Historical Transaction Statement': 'Relevé de Transactions Historique',
    'Financial Statement Report': 'Rapport d\'État Financier',
    'STATEMENT OF ACCOUNT': 'RELEVÉ DE COMPTE',
    'Period': 'Période',
    'Generated': 'Généré',
    'at': 'à',
    'Prepared For': 'Préparé Pour',
    'Account Tier': 'Niveau de Compte',
    'Financial Metrics Summary': 'Résumé des Métriques Financières',
    'Total Cash Inflow': 'Entrée de Trésorerie Totale',
    'Total Cash Outflow': 'Sortie de Trésorerie Totale',
    'Spending by Category Breakdown': 'Répartition des Dépenses par Catégorie',
    'Proportion': 'Proportion',
    'Transaction Details (Account Activity)': 'Détails des Transactions (Activité du Compte)',
    'This document is a certified summary of personal financial statements processed by FINAI. Information is prepared for reference purposes and is not formal legal tax auditing advice.': 'Ce document est un résumé certifié des états financiers personnels traités par FINAI. Les informations sont préparées à des fins de référence et ne constituent pas un conseil formel d\'audit fiscal juridique.',
    'Close': 'Fermer',
    'Download PDF': 'Télécharger le PDF',
  }
};

export function t(key: string, defaultText?: string): string {
  const lang = localStorage.getItem('finai_display_language') || 'English (US)';
  const langDict = translations[lang];
  if (langDict && langDict[key] !== undefined) {
    return langDict[key];
  }
  return defaultText !== undefined ? defaultText : key;
}
